//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_INDIVIDUAL
#define APIMATIC_INDIVIDUAL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Individual
@end

@interface Individual : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property NSString* firstName;

/**
* TODO: Write general description for this field
*/
@property NSString* lastName;

/**
* TODO: Write general description for this field
*/
@property NSString* email;

/**
* TODO: Write general description for this field
*/
@property NSString* avatar;

/**
* TODO: Write general description for this field
*/
@property int sessionId;

/**
* TODO: Write general description for this field
*/
@property NSString* mobileNumber;

/**
* TODO: Write general description for this field
*/
@property BOOL confirmed;

/**
* TODO: Write general description for this field
*/
@property NSString* loginMethod;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequest;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestDoctorId;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestDoctorFirstName;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestDoctorLastName;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestStatus;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestPatientLatitude;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestPatientLongitude;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestDoctorLatitude;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestDoctorLongitude;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestCreatedAt;

/**
* TODO: Write general description for this field
*/
@property NSString* activeRequestWillTimeoutAt;

/**
* TODO: Write general description for this field
*/
@property int doctorRequestStatus;

/**
* TODO: Write general description for this field
*/
@property NSString* authenticationToken;

/**
* TODO: Write general description for this field
*/
@property BOOL isAvailable;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif