//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_INDIVIDUAL2
#define APIMATIC_INDIVIDUAL2

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Individual2
@end

@interface Individual2 : JSONModel

/**
* TODO: Write general description for this field
*/
@property int mid;

/**
* TODO: Write general description for this field
*/
@property NSString* birthDate;

/**
* TODO: Write general description for this field
*/
@property NSString* gender;

/**
* TODO: Write general description for this field
*/
@property NSString* bloodGroup;

/**
* TODO: Write general description for this field
*/
@property NSString* relationshipStatus;

/**
* TODO: Write general description for this field
*/
@property NSString* childrenNumber;

/**
* TODO: Write general description for this field
*/
@property NSString* notes;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif