//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_LABREQUESTIMAGESGROUP
#define APIMATIC_LABREQUESTIMAGESGROUP

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "LabRequestImage.h"


//protocol defined for deserialization of JSON
@protocol LabRequestImagesGroup
@end

@interface LabRequestImagesGroup : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSString* mid;

/**
* TODO: Write general description for this field
*/
@property NSArray<LabRequestImage> * labRequestImages;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif