//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_LISTPRESCRIPTIONSGROUPSUNDERCERTAINCLINICVISIT
#define APIMATIC_LISTPRESCRIPTIONSGROUPSUNDERCERTAINCLINICVISIT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "PrescriptionImagesGroup.h"


//protocol defined for deserialization of JSON
@protocol ListPrescriptionsgroupsundercertainclinicvisit
@end

@interface ListPrescriptionsgroupsundercertainclinicvisit : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSArray* prescriptions;

/**
* TODO: Write general description for this field
*/
@property NSArray<PrescriptionImagesGroup> * prescriptionImagesGroups;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif