//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_LISTRADIOLOGYREQUESTGROUPFILE
#define APIMATIC_LISTRADIOLOGYREQUESTGROUPFILE

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "RadiologyRequestImageGroup.h"


//protocol defined for deserialization of JSON
@protocol Listradiologyrequestgroupfile
@end

@interface Listradiologyrequestgroupfile : JSONModel

/**
* TODO: Write general description for this field
*/
@property NSArray* radiologyRequests;

/**
* TODO: Write general description for this field
*/
@property NSArray<RadiologyRequestImageGroup> * radiologyRequestImageGroups;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif