//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_MRECOMMENT
#define APIMATIC_MRECOMMENT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Individual3.h"


//protocol defined for deserialization of JSON
@protocol MreComment
@end

@interface MreComment : JSONModel

/**
* TODO: Write general description for this field
*/
@property int commentId;

/**
* TODO: Write general description for this field
*/
@property NSString* body;

/**
* TODO: Write general description for this field
*/
@property int createdAt;

/**
* TODO: Write general description for this field
*/
@property int updatedAt;

/**
* TODO: Write general description for this field
*/
@property Individual3* individual;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif