//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "MreComment.h"

@implementation MreComment

/**
* TODO: Write general description for this method
*/
@synthesize commentId;

/**
* TODO: Write general description for this method
*/
@synthesize body;

/**
* TODO: Write general description for this method
*/
@synthesize createdAt;

/**
* TODO: Write general description for this method
*/
@synthesize updatedAt;

/**
* TODO: Write general description for this method
*/
@synthesize individual;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"comment_id": @"commentId",
        @"body": @"body",
        @"created_at": @"createdAt",
        @"updated_at": @"updatedAt",
        @"individual": @"individual"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end