//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import "UnauthorizedException.h"
@implementation UnauthorizedException

/**
* TODO: Write general description for this method
*/
@synthesize errors;


- (UnauthorizedException*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context
{
    self = [super initWithReason:reason andContext:context];
    return self;
}

- (void) unbox
{
    NSDictionary* data = [APIHelper jsonDeserializeObject: self.context.response.rawBody];
    errors = [data objectForKey: @"errors"];
}
@end