//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "APIError.h"
#import "HttpContext.h"
#import "Errors.h"



@interface UnauthorizedException : APIError
 
 /**
* TODO: Write general description for this field
*/
@property Errors* errors;

- (UnauthorizedException*) initWithReason: (NSString*) reason
                                  andContext: (HttpContext*) context;

@end