//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "AddnewallergyRequest.h"
#import "UpdateallergyRequest.h"

@interface AllergiesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5AllergiesPost */
typedef void (^CompletedPostApiV5AllergiesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) createApiV5AllergiesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(AddnewallergyRequest*) body
                completionBlock:(CompletedPostApiV5AllergiesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Allergies260Put */
typedef void (^CompletedPutApiV5Allergies260Put)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) updateApiV5Allergies260PutAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(UpdateallergyRequest*) body
                completionBlock:(CompletedPutApiV5Allergies260Put) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5AllergiesAutocompleteGet */
typedef void (^CompletedGetApiV5AllergiesAutocompleteGet)(BOOL success, HttpContext* context, NSError* error);

/**
* get static list of chronic diseases names
* @param    term    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5AllergiesAutocompleteGetAsyncWithTerm:(NSString*) term
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5AllergiesAutocompleteGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Allergies255Get */
typedef void (^CompletedGetApiV5Allergies255Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5Allergies255GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5Allergies255Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5AllergiesGet */
typedef void (^CompletedGetApiV5AllergiesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5AllergiesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5AllergiesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Allergies260Delete */
typedef void (^CompletedDeleteApiV5Allergies260Delete)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) deleteApiV5Allergies260DeleteAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedDeleteApiV5Allergies260Delete) onCompleted;

@end