//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CreateRequest1.h"

@interface AppointmentsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5AppointmentRequestsPost */
typedef void (^CompletedPostApiV5AppointmentRequestsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) createApiV5AppointmentRequestsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(CreateRequest1*) body
                completionBlock:(CompletedPostApiV5AppointmentRequestsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5AppointmentRequestsGet */
typedef void (^CompletedGetApiV5AppointmentRequestsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5AppointmentRequestsGetAsyncWithPage:(int) page
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5AppointmentRequestsGet) onCompleted;

@end