//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "AddnewchronicdiseaseRequest.h"
#import "UpdatechronicdiseaseRequest.h"

@interface ChronicDiseasesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5ChronicDiseasesPost */
typedef void (^CompletedPostApiV5ChronicDiseasesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) createApiV5ChronicDiseasesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(AddnewchronicdiseaseRequest*) body
                completionBlock:(CompletedPostApiV5ChronicDiseasesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ChronicDiseases409Put */
typedef void (^CompletedPutApiV5ChronicDiseases409Put)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) updateApiV5ChronicDiseases409PutAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(UpdatechronicdiseaseRequest*) body
                completionBlock:(CompletedPutApiV5ChronicDiseases409Put) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ChronicDiseasesDiseasesListGet */
typedef void (^CompletedGetApiV5ChronicDiseasesDiseasesListGet)(BOOL success, HttpContext* context, NSError* error);

/**
* get static list of chronic diseases names
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ChronicDiseasesDiseasesListGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ChronicDiseasesDiseasesListGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ChronicDiseases399Get */
typedef void (^CompletedGetApiV5ChronicDiseases399Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ChronicDiseases399GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ChronicDiseases399Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ChronicDiseasesGet */
typedef void (^CompletedGetApiV5ChronicDiseasesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ChronicDiseasesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ChronicDiseasesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ChronicDiseases409Delete */
typedef void (^CompletedDeleteApiV5ChronicDiseases409Delete)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) deleteApiV5ChronicDiseases409DeleteAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedDeleteApiV5ChronicDiseases409Delete) onCompleted;

@end