//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface CommentsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5News574efc7969702d370a130000CommentsGet */
typedef void (^CompletedGetApiV5News574efc7969702d370a130000CommentsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* Index comments with pagination 
* params[:page] = page number
* returns all comments
* returns 5 comments per page
* @param    page    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
*/
- (void) getApiV5News574efc7969702d370a130000CommentsGetAsyncWithPage:(int) page
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                completionBlock:(CompletedGetApiV5News574efc7969702d370a130000CommentsGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5News580f73426d61725cae000000CommentsPost */
typedef void (^CompletedPostApiV5News580f73426d61725cae000000CommentsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    commentBody    Required parameter: Example: 
*/
- (void) createApiV5News580f73426d61725cae000000CommentsPostAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                commentBody:(NSString*) commentBody
                completionBlock:(CompletedPostApiV5News580f73426d61725cae000000CommentsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000Put */
typedef void (^CompletedPutApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000Put)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    commentBody    Required parameter: Example: 
*/
- (void) updateApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000PutAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                commentBody:(NSString*) commentBody
                completionBlock:(CompletedPutApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000Put) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000Delete */
typedef void (^CompletedDeleteApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000Delete)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
*/
- (void) deleteApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000DeleteAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                completionBlock:(CompletedDeleteApiV5News5908b86669702d0d34090000Comments5912e99469702d330f170000Delete) onCompleted;

@end