//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface ConfirmationController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5ConfirmationsSendConfirmationSmsPost */
typedef void (^CompletedPostApiV5ConfirmationsSendConfirmationSmsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xStatus    Required parameter: Example: 
* @param    individualId    Required parameter: Example: 
* @param    individualMobileNumber    Required parameter: Example: 
*/
- (void) createApiV5ConfirmationsSendConfirmationSmsPostAsyncWithXStatus:(NSString*) xStatus
                individualId:(NSString*) individualId
                individualMobileNumber:(NSString*) individualMobileNumber
                completionBlock:(CompletedPostApiV5ConfirmationsSendConfirmationSmsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ConfirmationsConfirmEmailGet */
typedef void (^CompletedGetApiV5ConfirmationsConfirmEmailGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    individualId    Required parameter: Example: 
* @param    email    Required parameter: Example: 
* @param    confirmationCode    Required parameter: Example: 
* @param    xStatus    Required parameter: Example: 
*/
- (void) getApiV5ConfirmationsConfirmEmailGetAsyncWithIndividualId:(int) individualId
                email:(NSString*) email
                confirmationCode:(NSString*) confirmationCode
                xStatus:(NSString*) xStatus
                completionBlock:(CompletedGetApiV5ConfirmationsConfirmEmailGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ConfirmationsConfirmMobileGet */
typedef void (^CompletedGetApiV5ConfirmationsConfirmMobileGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    individualId    Required parameter: Example: 
* @param    mobileNumber    Required parameter: Example: 
* @param    confirmationCode    Required parameter: Example: 
* @param    xStatus    Required parameter: Example: 
*/
- (void) getApiV5ConfirmationsConfirmMobileGetAsyncWithIndividualId:(int) individualId
                mobileNumber:(double) mobileNumber
                confirmationCode:(int) confirmationCode
                xStatus:(NSString*) xStatus
                completionBlock:(CompletedGetApiV5ConfirmationsConfirmMobileGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ConfirmationsSendConfirmationMailPost */
typedef void (^CompletedPostApiV5ConfirmationsSendConfirmationMailPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xStatus    Required parameter: Example: 
* @param    individualId    Required parameter: Example: 
* @param    individualEmail    Required parameter: Example: 
*/
- (void) createApiV5ConfirmationsSendConfirmationMailPostAsyncWithXStatus:(NSString*) xStatus
                individualId:(NSString*) individualId
                individualEmail:(NSString*) individualEmail
                completionBlock:(CompletedPostApiV5ConfirmationsSendConfirmationMailPost) onCompleted;

@end