//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface CrossBorderTreatmentsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5CrmCrossBorderTreatmentRequestsGet */
typedef void (^CompletedGetApiV5CrmCrossBorderTreatmentRequestsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    page    Required parameter: Example: 
* @param    perPage    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
*/
- (void) getApiV5CrmCrossBorderTreatmentRequestsGetAsyncWithPage:(int) page
                perPage:(int) perPage
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                completionBlock:(CompletedGetApiV5CrmCrossBorderTreatmentRequestsGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5CrossBorderTreatmentRequestsPost */
typedef void (^CompletedPostApiV5CrossBorderTreatmentRequestsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    contentType    Required parameter: Example: 
* @param    crossBorderTreatmentName    Required parameter: Example: 
* @param    crossBorderTreatmentTelephoneNumber    Required parameter: Example: 
* @param    crossBorderTreatmentEmail    Required parameter: Example: 
* @param    crossBorderTreatmentDiagnosis    Required parameter: Example: 
* @param    crossBorderTreatmentTreatmentGroupId    Required parameter: Example: 
* @param    crossBorderTreatmentCountry    Required parameter: Example: 
* @param    crossBorderTreatmentRequestType    Required parameter: Example: 
*/
- (void) createApiV5CrossBorderTreatmentRequestsPostAsyncWithContentType:(NSString*) contentType
                crossBorderTreatmentName:(NSString*) crossBorderTreatmentName
                crossBorderTreatmentTelephoneNumber:(NSString*) crossBorderTreatmentTelephoneNumber
                crossBorderTreatmentEmail:(NSString*) crossBorderTreatmentEmail
                crossBorderTreatmentDiagnosis:(NSString*) crossBorderTreatmentDiagnosis
                crossBorderTreatmentTreatmentGroupId:(NSString*) crossBorderTreatmentTreatmentGroupId
                crossBorderTreatmentCountry:(NSString*) crossBorderTreatmentCountry
                crossBorderTreatmentRequestType:(NSString*) crossBorderTreatmentRequestType
                completionBlock:(CompletedPostApiV5CrossBorderTreatmentRequestsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5CrossBorderTreatmentsGet */
typedef void (^CompletedGetApiV5CrossBorderTreatmentsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* -params[:type]  can be set as hospital or clinic
*       if not set at all the default is clinics only
* -params[:treatments] comma seperated treatments ids to filter with
* -params[:speciality_id] 
* -params[:country_codes] comma country codes ids to filter with
* -params[:country_code] for old apis to work send 1 country code to filter by
* cross border treatments should be sorted by price
* @param    type    Required parameter: Example: 
*/
- (void) getApiV5CrossBorderTreatmentsGetAsyncWithType:(NSString*) type
                completionBlock:(CompletedGetApiV5CrossBorderTreatmentsGet) onCompleted;

/**
* Completion block definition for asynchronous call to StatesGet */
typedef void (^CompletedGetStatesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    countryCode    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getStatesGetAsyncWithCountryCode:(NSString*) countryCode
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetStatesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5CrossBorderTreatmentsCountriesGet */
typedef void (^CompletedGetApiV5CrossBorderTreatmentsCountriesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5CrossBorderTreatmentsCountriesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5CrossBorderTreatmentsCountriesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5TreatmentsGroupsGet */
typedef void (^CompletedGetApiV5TreatmentsGroupsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    lang    Required parameter: Example: 
*/
- (void) getApiV5TreatmentsGroupsGetAsyncWithLang:(NSString*) lang
                completionBlock:(CompletedGetApiV5TreatmentsGroupsGet) onCompleted;

@end