//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface DrugsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5DrugsGet */
typedef void (^CompletedGetApiV5DrugsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    active    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5DrugsGetAsyncWithActive:(int) active
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5DrugsGet) onCompleted;

@end