//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface EditProfileController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5UpdateProfilePatch */
typedef void (^CompletedPatchApiV5UpdateProfilePatch)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    individualFirstName    Required parameter: Example: 
* @param    individualLastName    Required parameter: Example: 
* @param    individualAvatar    Required parameter: Example: 
* @param    individualAddressStreet    Required parameter: Example: 
* @param    individualAddressBuilding    Required parameter: Example: 
* @param    individualAddressCity    Required parameter: Example: 
* @param    individualAddressCountry    Required parameter: Example: 
*/
- (void) updateApiV5UpdateProfilePatchAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                individualFirstName:(NSString*) individualFirstName
                individualLastName:(NSString*) individualLastName
                individualAvatar:(NSString*) individualAvatar
                individualAddressStreet:(NSString*) individualAddressStreet
                individualAddressBuilding:(NSString*) individualAddressBuilding
                individualAddressCity:(NSString*) individualAddressCity
                individualAddressCountry:(NSString*) individualAddressCountry
                completionBlock:(CompletedPatchApiV5UpdateProfilePatch) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5IndividualsEditIdentifierPost */
typedef void (^CompletedPostApiV5IndividualsEditIdentifierPost)(BOOL success, HttpContext* context, NSError* error);

/**
* first step to edit .. 
* sends confirmation and save it in the cache
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    identifier    Required parameter: Example: 
* @param    type    Required parameter: Example: 
*/
- (void) createApiV5IndividualsEditIdentifierPostAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                identifier:(NSString*) identifier
                type:(NSString*) type
                completionBlock:(CompletedPostApiV5IndividualsEditIdentifierPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5IndividualsUpdateIdentifierPost */
typedef void (^CompletedPostApiV5IndividualsUpdateIdentifierPost)(BOOL success, HttpContext* context, NSError* error);

/**
* final step to confirm the update ..
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    identifier    Required parameter: Example: 
* @param    confirmationCode    Required parameter: Example: 
* @param    type    Required parameter: Example: 
*/
- (void) createApiV5IndividualsUpdateIdentifierPostAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                identifier:(NSString*) identifier
                confirmationCode:(NSString*) confirmationCode
                type:(NSString*) type
                completionBlock:(CompletedPostApiV5IndividualsUpdateIdentifierPost) onCompleted;

@end