//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "NSDate+extension.h"

@interface GeneralController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5SpecialitiesWithCareerLevelsGet */
typedef void (^CompletedGetApiV5SpecialitiesWithCareerLevelsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* Return career levels with specialities
*/
- (void) getApiV5SpecialitiesWithCareerLevelsGetWithCompletionBlock:(CompletedGetApiV5SpecialitiesWithCareerLevelsGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5SearchGet */
typedef void (^CompletedGetApiV5SearchGet)(BOOL success, HttpContext* context, NSError* error);

/**
* Search news
* @param    q    Required parameter: Example: 
*/
- (void) getApiV5SearchGetAsyncWithQ:(NSString*) q
                completionBlock:(CompletedGetApiV5SearchGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5AppVersionGet */
typedef void (^CompletedGetApiV5AppVersionGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    appVersion    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    userAgent    Required parameter: Example: 
*/
- (void) getApiV5AppVersionGetAsyncWithAppVersion:(NSDate*) appVersion
                xAppId:(NSString*) xAppId
                userAgent:(NSString*) userAgent
                completionBlock:(CompletedGetApiV5AppVersionGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5DoctorRequestsPost */
typedef void (^CompletedPostApiV5DoctorRequestsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    careerLevelId    Required parameter: Example: 
* @param    specialityId    Required parameter: Example: 
* @param    mobileNumber    Required parameter: Example: 
*/
- (void) createApiV5DoctorRequestsPostAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                careerLevelId:(NSString*) careerLevelId
                specialityId:(NSString*) specialityId
                mobileNumber:(NSString*) mobileNumber
                completionBlock:(CompletedPostApiV5DoctorRequestsPost) onCompleted;

@end