//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface IndividualImagesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5IndividualImagesPost */
typedef void (^CompletedPostApiV5IndividualImagesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    individualImageImage    Required parameter: Example: 
*/
- (void) createApiV5IndividualImagesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                individualImageImage:(NSString*) individualImageImage
                completionBlock:(CompletedPostApiV5IndividualImagesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5IndividualImages2Get */
typedef void (^CompletedGetApiV5IndividualImages2Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5IndividualImages2GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5IndividualImages2Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5IndividualImagesGet */
typedef void (^CompletedGetApiV5IndividualImagesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5IndividualImagesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5IndividualImagesGet) onCompleted;

@end