//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface LabRequestImagesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5LabRequestImagesGet */
typedef void (^CompletedGetApiV5LabRequestImagesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5LabRequestImagesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5LabRequestImagesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5LabRequestImages58d23b9b5461720ee2000000Get */
typedef void (^CompletedGetApiV5LabRequestImages58d23b9b5461720ee2000000Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5LabRequestImages58d23b9b5461720ee2000000GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5LabRequestImages58d23b9b5461720ee2000000Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests3756LabRequestImagesPost */
typedef void (^CompletedPostApiV5ReservationRequests3756LabRequestImagesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    labRequestImageImage    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequests3756LabRequestImagesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                labRequestImageImage:(NSString*) labRequestImageImage
                completionBlock:(CompletedPostApiV5ReservationRequests3756LabRequestImagesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests3827LabRequestImagesGet */
typedef void (^CompletedGetApiV5ReservationRequests3827LabRequestImagesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests3827LabRequestImagesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests3827LabRequestImagesGet) onCompleted;

@end