//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "IndexlabrequestsgroupsforreservationrequestClinicvisit.h"

@interface LabRequestGroupsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5LabRequestGroupsGet */
typedef void (^CompletedGetApiV5LabRequestGroupsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5LabRequestGroupsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5LabRequestGroupsGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2631LabRequestGroupsGet */
typedef void (^CompletedGetApiV5ReservationRequests2631LabRequestGroupsGet)(BOOL success, HttpContext* context, IndexlabrequestsgroupsforreservationrequestClinicvisit* response, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests2631LabRequestGroupsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests2631LabRequestGroupsGet) onCompleted;

@end