//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface LifestylesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5LifeStylesPost */
typedef void (^CompletedPostApiV5LifeStylesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    lifeStyleKey    Required parameter: Example: 
* @param    lifeStyleValue    Required parameter: Example: 
*/
- (void) createApiV5LifeStylesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                lifeStyleKey:(NSString*) lifeStyleKey
                lifeStyleValue:(NSString*) lifeStyleValue
                completionBlock:(CompletedPostApiV5LifeStylesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5LifeStyles1615Put */
typedef void (^CompletedPutApiV5LifeStyles1615Put)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    lifeStyleKey    Required parameter: Example: 
* @param    lifeStyleValue    Required parameter: Example: 
*/
- (void) updateApiV5LifeStyles1615PutAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                lifeStyleKey:(NSString*) lifeStyleKey
                lifeStyleValue:(NSString*) lifeStyleValue
                completionBlock:(CompletedPutApiV5LifeStyles1615Put) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5LifeStylesListLifeStylesGet */
typedef void (^CompletedGetApiV5LifeStylesListLifeStylesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5LifeStylesListLifeStylesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5LifeStylesListLifeStylesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5LifeStylesGet */
typedef void (^CompletedGetApiV5LifeStylesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5LifeStylesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5LifeStylesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5LifeStyles1615Delete */
typedef void (^CompletedDeleteApiV5LifeStyles1615Delete)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) deleteApiV5LifeStyles1615DeleteAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedDeleteApiV5LifeStyles1615Delete) onCompleted;

@end