//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "Listradiologyrequestgroupfile.h"

@interface ListRadiologyRequestGroupsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5RadiologyRequestGroupsGet */
typedef void (^CompletedGetApiV5RadiologyRequestGroupsGet)(BOOL success, HttpContext* context, Listradiologyrequestgroupfile* response, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5RadiologyRequestGroupsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5RadiologyRequestGroupsGet) onCompleted;

@end