//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface MeasurementsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5DiabetesAddPost */
typedef void (^CompletedPostApiV5DiabetesAddPost)(BOOL success, HttpContext* context, NSError* error);

/**
* # Specifications :-
* <b>URL : </b>/diabetes/add  
* <b>Method : </b>POST  
* # Parameters :-
* <b>Headers :</b>  
* 1- X-Authentication-Token  
* 2- X-Session-Id  
* 3- X-App-Id : should be sent only when using doctor app  
* <b>Params :</b>  
* -diabetes : String contains fields data in json (array) format  
* Ex: "[{ 'field_name': "" }]" --> string "[]" not json object/array  
* Each Object in the array consists of:  
* 1- field_name  
* 2- field_value  
* 3- date Or date_timestamp (with date_timestamp you don't need to send date field again in the relations array)  
* 4- relations => Array_of_relations  
* Every relation in the array consists of the same previous attributes/keys  
* ( date, field_name, field_value )  
* <b>Note in Pregnancy App</b>  
* "field_name" param possible values are => glucose, blood_pressure, weight  
* When the "field_name" value is glucose then the "field_name" value inside the relations will be  => "last meal", "activity"  
* The "last meal" "field_value" could be => Before Breakfast, After Breakfast, Before Lunch, After Lunch, At Fasting  
* The "activity"  "field_value" could be => No exercise, Light, Moderate, Heavy  
* # Response/JSON :-
* 1- {}, status: :ok  
* 2- {}, status: :unprocessable_entity
* @param    diabetes    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) createApiV5DiabetesAddPostAsyncWithDiabetes:(NSString*) diabetes
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedPostApiV5DiabetesAddPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5DiabetesGetSummaryGet */
typedef void (^CompletedGetApiV5DiabetesGetSummaryGet)(BOOL success, HttpContext* context, NSError* error);

/**
* # Specifications :-
* <b>URL : </b>/diabetes/get_summary  
* <b>Method : </b>GET  
* # Parameters :-
* <b>Headers :</b>  
* 1- X-Authentication-Token  
* 2- X-Session-Id  
* 3- X-App-Id : should be sent only when using doctor app  
* # Response/JSON :-
* 1- <b>{measurements: Array_of_values}, status: :ok</b>  
* &nbsp;&nbsp;Every Value in the array (sorted by date) consists of:  
* &nbsp;&nbsp;1- created_at  
* &nbsp;&nbsp;2- date  
* &nbsp;&nbsp;3- date_timestamp  
* &nbsp;&nbsp;4- field_name  
* &nbsp;&nbsp;5- field_value  
* &nbsp;&nbsp;6- id  
* &nbsp;&nbsp;7- is_pmr  
* &nbsp;&nbsp;8- updated_at  
* &nbsp;&nbsp;9- user_id  
* &nbsp;&nbsp;10- relations   => Array_of_relations  
* &nbsp;&nbsp;&nbsp;&nbsp;Every relation in the array consists of the same previous attributes/keys  
* &nbsp;&nbsp;&nbsp;&nbsp;( created_at, date, field_name, field_value, id, is_pmr, updated_at, user_id )  
* 2- <b>{}, status: :unprocessable_entity</b>
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) getApiV5DiabetesGetSummaryGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedGetApiV5DiabetesGetSummaryGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5DiabetesGetGet */
typedef void (^CompletedGetApiV5DiabetesGetGet)(BOOL success, HttpContext* context, NSError* error);

/**
* # Specifications :-
* <b>URL : </b>/diabetes/get  
* <b>Method : </b>GET  
* <b>Description : </b>retrieve the corresponding diabetes info to the provided user with the diabetes type and build back the relations if it exists  
* # Parameters :-
* <b>Headers :</b>  
* 1- X-Authentication-Token  
* 2- X-Session-Id  
* 3- X-App-Id : should be sent only when using doctor app  
* <b>Params :</b>  
* 1- type  
* <b>Note in Pregnancy App</b>  
* "type" param possible values are => glucose, blood_pressure, weight
* # Response/JSON :-
* 1- <b>{measurements: Array_of_values}, status: :ok</b>  
* &nbsp;&nbsp;Every Value in the array (sorted by date) consists of:  
* &nbsp;&nbsp;1- created_at  
* &nbsp;&nbsp;2- date  
* &nbsp;&nbsp;3- date_timestamp  
* &nbsp;&nbsp;4- field_name  
* &nbsp;&nbsp;5- field_value  
* &nbsp;&nbsp;6- id  
* &nbsp;&nbsp;7- is_pmr  
* &nbsp;&nbsp;8- updated_at  
* &nbsp;&nbsp;9- user_id  
* &nbsp;&nbsp;10- relations   => Array_of_relations  
* &nbsp;&nbsp;&nbsp;&nbsp;Every relation in the array consists of the same previous attributes/keys  
* &nbsp;&nbsp;&nbsp;&nbsp;( created_at, date, field_name, field_value, id, is_pmr, updated_at, user_id )  
* 2- <b>{}, status: :unprocessable_entity</b>
* @param    type    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) getApiV5DiabetesGetGetAsyncWithType:(NSString*) type
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedGetApiV5DiabetesGetGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5DiabetesVisualizedDataPost */
typedef void (^CompletedPostApiV5DiabetesVisualizedDataPost)(BOOL success, HttpContext* context, NSError* error);

/**
* # Specifications :-
* <b>URL : </b>/diabetes/visualized_data  
* <b>Method : </b>POST  
* # Parameters :-
* <b>Headers :</b>  
* 1- X-Authentication-Token  
* 2- X-Session-Id  
* 3- X-App-Id : should be sent only when using doctor app  
* <b>Params :</b>  
* 1- send_email  
* 2- type  
* <b>Note in Pregnancy App</b>  
* "type" param possible values are => glucose, blood_pressure, weight  
* # Response/JSON :-
* 1- <b>{"message":"mail sent"}, status: :ok</b>  
* 2- <b>{:graph => graph_url, count: count}, status: :ok</b>  
* 3- <b>{}, status: :unprocessable_entity</b>  
* providing Graph to the matched requested diabetes info  
* Two cases will apply:  
* 1- if the request is to send email contains the graph url to some one provided in the request params e.g "send_email: bla@bla.bla"  
* 2- if the request is just to get the corresponding graph to the matched [type, user]  
* @param    sendEmail    Required parameter: Example: 
* @param    type    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
*/
- (void) createApiV5DiabetesVisualizedDataPostAsyncWithSendEmail:(NSString*) sendEmail
                type:(NSString*) type
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xAppId:(NSString*) xAppId
                completionBlock:(CompletedPostApiV5DiabetesVisualizedDataPost) onCompleted;

@end