//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface MessagesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5MessagesGetGet */
typedef void (^CompletedGetApiV5MessagesGetGet)(BOOL success, HttpContext* context, NSError* error);

/**
*  # URL         => /messages/get
*   # Method      => GET
*   # Description => Get List of Messages
*   #==Parameters
*   # range => represent the number of messages per page (default => 500)
*   # page  => page number (default => 1)
*   # email => curent user email
*   # authentication_token => curent user authentication_token (you get this token after login/registration)
*   #==Response/JSON
*   # {success: true , messages: array_of_messages}
*   # Every message in the array consists of:
*   # 1. date    => last reply date (Or message creation date if no replies)
*   # 2. date_unix_timestamp
*   # 3. id      => message id
*   # 4. title   => message title
*   # 5. is_seen => 1/0
*   # 6. is_sent => 1/0
*   # 7. Array_of_Users
*   #   Every user in the array consists of:
*   #     1. first_name
*   #     2. id
*   #     3. avatar => Object
*   #           {url: value , icon: {url: value},thumb: {url: value}, profile: {url: value}, profile_big: {url: value} }
*   # 8. last_reply => last reply on the message
*   #
*   # NOTE: In case of error response will be => {sucess: false , code: error_code , message: error_message }
*   # Errors:
*   #   1. UnauthorizedAccessError ( code: 401 )
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5MessagesGetGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5MessagesGetGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5MessagesGetRepliesGet */
typedef void (^CompletedGetApiV5MessagesGetRepliesGet)(BOOL success, HttpContext* context, NSError* error);

/**
*  # URL         => /messages/get_replies
*   # Method      => GET
*   # Description => Get List of Message Replies
*   #==Parameters
*   # range      => represent the number of replies per page (default => 500)
*   # page       => page number (default => 1)
*   # message_id => id of the messages which the required replies belongs to
*   # email      => curent user email
*   # authentication_token => curent user authentication_token (you get this token after login/registration)
*   #==Response/JSON
*   # {success: true , replies: array_of_replies}
*   # array_of_replies => including the 'message' itself
*   # Every Reply in the array consists of:
*   # 1. date    => creation date
*   # 2. date_unix_timestamp
*   # 3. body    => reply/message content
*   # 4. id
*   # 5. user    => owner of the current reply/message
*   #     Object consists of:
*   #     1. full_name
*   #     2. id
*   #     3. avatar => Object
*   #           {url: value , icon: {url: value},thumb: {url: value}, profile: {url: value}, profile_big: {url: value} }
*   #
*   # NOTE: In case of error response will be => {sucess: false , code: error_code , message: error_message }
*   # Errors:
*   #   1. UnauthorizedAccessError ( code: 401 )
*   #   2. BadRequestError ( code: 400 )
*   #   3. NotFoundError   ( code: 404 )
* @param    messageId    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5MessagesGetRepliesGetAsyncWithMessageId:(int) messageId
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5MessagesGetRepliesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5MessagesSendMessagePost */
typedef void (^CompletedPostApiV5MessagesSendMessagePost)(BOOL success, HttpContext* context, NSError* error);

/**
* # URL         => /messages/send_message
*   # Method      => POST
*   #==Parameters
*   # title
*   # body
*   # users_ids  => comma seperated ids of the receivers (ex: 256,10365)
*   # email      => curent user email
*   # authentication_token => curent user authentication_token (you get this token after login/registration)
*   #==Response/JSON
*   # { success: true }
*   #
*   # NOTE: In case of error response will be => {sucess: false , code: error_code , message: error_message }
*   # Errors:
*   #   1. UnauthorizedAccessError ( code: 401 )
*   #   2. BadRequestError         ( code: 400 )
*   #==Description
*   # this function send message to required receiver, in case many receivers => a different message
*   # will be created for each receiver (one to one)
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    title    Required parameter: Example: 
* @param    body    Required parameter: Example: 
* @param    usersIds    Required parameter: Example: 
* @param    attachment    Required parameter: Example: 
*/
- (void) createApiV5MessagesSendMessagePostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                title:(NSString*) title
                body:(NSString*) body
                usersIds:(NSString*) usersIds
                attachment:(NSString*) attachment
                completionBlock:(CompletedPostApiV5MessagesSendMessagePost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5MessagesSendReplyPost */
typedef void (^CompletedPostApiV5MessagesSendReplyPost)(BOOL success, HttpContext* context, NSError* error);

/**
* # URL       => /messages/send_reply
*   # Method    => POST
*   #==Parameters
*   # body       => reply content
*   # message_id => send reply to the message with that ID
*   # email      => curent user email
*   # authentication_token => curent user authentication_token (you get this token after login/registration)
*   #==Response/JSON
*   # { success: true }
*   #
*   # NOTE: In case of error response will be => {sucess: false , code: error_code , message: error_message }
*   # Errors:
*   #   1. UnauthorizedAccessError ( code: 401 )
*   #   2. BadRequestError         ( code: 400 )
*   #   3. ForbiddenError          ( code: 403 )
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    body    Required parameter: Example: 
* @param    messageId    Required parameter: Example: 
*/
- (void) createApiV5MessagesSendReplyPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                body:(NSString*) body
                messageId:(NSString*) messageId
                completionBlock:(CompletedPostApiV5MessagesSendReplyPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5MessagesSearchUsersGet */
typedef void (^CompletedGetApiV5MessagesSearchUsersGet)(BOOL success, HttpContext* context, NSError* error);

/**
*  # URL         => /messages/search_users
*   # Method      => GET
*   # Description => Search for the users which you are able to send them messages
*   #                Staff to Staff and patients
*   #                Patients to Doctors
*   #                Doctors to Patients which have PMR access on them and vice versa
*   #==Parameters
*   # term  => search for a user with name contains this term/pattern
*   # range => (Optional) default range is 10
*   # email => curent user email
*   # authentication_token => curent user authentication_token (you get this token after login/registration)
*   #==Response/JSON
*   # {success: true , messages: array_of_users}
*   # Every user in the array consists of:
*   # 1. full_name    => user full name
*   # 2. id           => user id
*   # 3. avatar       => user images urls/ with different sizes
*   #     Object consists of:
*   #       {url: value , icon: {url: value},thumb: {url: value}, profile: {url: value}, profile_big: {url: value} }
*   #
*   # NOTE: In case of error response will be => {sucess: false , code: error_code , message: error_message }
*   # Errors:
*   #   1. UnauthorizedAccessError ( code: 401 )
*   #   2. BadRequestError         ( code: 400 )
* @param    term    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5MessagesSearchUsersGetAsyncWithTerm:(NSString*) term
                xSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5MessagesSearchUsersGet) onCompleted;

@end