//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface MiscController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5DoctorAvailabilityNotificationsPost */
typedef void (^CompletedPostApiV5DoctorAvailabilityNotificationsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    doctorAvailabilityNotificationSpecialityId    Required parameter: Example: 
* @param    doctorAvailabilityNotificationRequestType    Required parameter: Example: 
*/
- (void) createApiV5DoctorAvailabilityNotificationsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                doctorAvailabilityNotificationSpecialityId:(NSString*) doctorAvailabilityNotificationSpecialityId
                doctorAvailabilityNotificationRequestType:(NSString*) doctorAvailabilityNotificationRequestType
                completionBlock:(CompletedPostApiV5DoctorAvailabilityNotificationsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ContactRequestContactPost */
typedef void (^CompletedPostApiV5ContactRequestContactPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    contentType    Required parameter: Example: 
* @param    mailName    Required parameter: Example: 
* @param    mailEmail    Required parameter: Example: 
* @param    mailFormType    Required parameter: Example: 
* @param    mailMessage    Required parameter: Example: 
*/
- (void) createApiV5ContactRequestContactPostAsyncWithContentType:(NSString*) contentType
                mailName:(NSString*) mailName
                mailEmail:(NSString*) mailEmail
                mailFormType:(NSString*) mailFormType
                mailMessage:(NSString*) mailMessage
                completionBlock:(CompletedPostApiV5ContactRequestContactPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests3263MresVisitMedicalDataGet */
typedef void (^CompletedGetApiV5ReservationRequests3263MresVisitMedicalDataGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests3263MresVisitMedicalDataGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests3263MresVisitMedicalDataGet) onCompleted;

@end