//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface NewsTagsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5NewsTagsGet */
typedef void (^CompletedGetApiV5NewsTagsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
*/
- (void) getApiV5NewsTagsGetWithCompletionBlock:(CompletedGetApiV5NewsTagsGet) onCompleted;

@end