//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface PaypalController : BaseController

/**
* Completion block definition for asynchronous call to TokenPost */
typedef void (^CompletedPostTokenPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    contentType    Required parameter: Example: 
* @param    grantType    Required parameter: Example: 
*/
- (void) createTokenPostAsyncWithContentType:(NSString*) contentType
                grantType:(NSString*) grantType
                completionBlock:(CompletedPostTokenPost) onCompleted;

@end