//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface PrescriptionsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5PrescriptionsPost */
typedef void (^CompletedPostApiV5PrescriptionsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    prescriptionDate    Required parameter: Example: 
* @param    prescriptionPrescriber    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes0StartDate    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes0Num    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes0Duration    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes0DrugId    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes0Dose    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes0Notes    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes1461845708794StartDate    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes1461845708794Num    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes1461845708794Duration    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes1461845708794DrugId    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes1461845708794Dose    Required parameter: Example: 
* @param    prescriptionPresDrugsAttributes1461845708794Destroy    Required parameter: Example: 
*/
- (void) createApiV5PrescriptionsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                prescriptionDate:(NSString*) prescriptionDate
                prescriptionPrescriber:(NSString*) prescriptionPrescriber
                prescriptionPresDrugsAttributes0StartDate:(NSString*) prescriptionPresDrugsAttributes0StartDate
                prescriptionPresDrugsAttributes0Num:(NSString*) prescriptionPresDrugsAttributes0Num
                prescriptionPresDrugsAttributes0Duration:(NSString*) prescriptionPresDrugsAttributes0Duration
                prescriptionPresDrugsAttributes0DrugId:(NSString*) prescriptionPresDrugsAttributes0DrugId
                prescriptionPresDrugsAttributes0Dose:(NSString*) prescriptionPresDrugsAttributes0Dose
                prescriptionPresDrugsAttributes0Notes:(NSString*) prescriptionPresDrugsAttributes0Notes
                prescriptionPresDrugsAttributes1461845708794StartDate:(NSString*) prescriptionPresDrugsAttributes1461845708794StartDate
                prescriptionPresDrugsAttributes1461845708794Num:(NSString*) prescriptionPresDrugsAttributes1461845708794Num
                prescriptionPresDrugsAttributes1461845708794Duration:(NSString*) prescriptionPresDrugsAttributes1461845708794Duration
                prescriptionPresDrugsAttributes1461845708794DrugId:(NSString*) prescriptionPresDrugsAttributes1461845708794DrugId
                prescriptionPresDrugsAttributes1461845708794Dose:(NSString*) prescriptionPresDrugsAttributes1461845708794Dose
                prescriptionPresDrugsAttributes1461845708794Destroy:(NSString*) prescriptionPresDrugsAttributes1461845708794Destroy
                completionBlock:(CompletedPostApiV5PrescriptionsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests4271PrescriptionsGet */
typedef void (^CompletedGetApiV5ReservationRequests4271PrescriptionsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests4271PrescriptionsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests4271PrescriptionsGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Prescriptions5a1bf82474617232620b0000Get */
typedef void (^CompletedGetApiV5Prescriptions5a1bf82474617232620b0000Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5Prescriptions5a1bf82474617232620b0000GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5Prescriptions5a1bf82474617232620b0000Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests46464634Prescriptions5a1bf82474617232620b0000Get */
typedef void (^CompletedGetApiV5ReservationRequests46464634Prescriptions5a1bf82474617232620b0000Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests46464634Prescriptions5a1bf82474617232620b0000GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests46464634Prescriptions5a1bf82474617232620b0000Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5PrescriptionsGet */
typedef void (^CompletedGetApiV5PrescriptionsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5PrescriptionsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5PrescriptionsGet) onCompleted;

@end