//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface PrescriptionImagesGroupController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2668PrescriptionImagesGroupsPost */
typedef void (^CompletedPostApiV5ReservationRequests2668PrescriptionImagesGroupsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xAppId    Required parameter: Example: 
* @param    prescriptionImagesGroupPrescriptionImagesAttributesImage    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequests2668PrescriptionImagesGroupsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                xAppId:(NSString*) xAppId
                prescriptionImagesGroupPrescriptionImagesAttributesImage:(NSString*) prescriptionImagesGroupPrescriptionImagesAttributesImage
                completionBlock:(CompletedPostApiV5ReservationRequests2668PrescriptionImagesGroupsPost) onCompleted;

@end