//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface PrescriptionImagesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5PrescriptionImagesGet */
typedef void (^CompletedGetApiV5PrescriptionImagesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5PrescriptionImagesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5PrescriptionImagesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5PrescriptionImages58d23b9b5461720ee2000000Get */
typedef void (^CompletedGetApiV5PrescriptionImages58d23b9b5461720ee2000000Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5PrescriptionImages58d23b9b5461720ee2000000GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5PrescriptionImages58d23b9b5461720ee2000000Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2668PrescriptionImagesPost */
typedef void (^CompletedPostApiV5ReservationRequests2668PrescriptionImagesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    prescriptionImageImage    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequests2668PrescriptionImagesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                prescriptionImageImage:(NSString*) prescriptionImageImage
                completionBlock:(CompletedPostApiV5ReservationRequests2668PrescriptionImagesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2668PrescriptionImagesGet */
typedef void (^CompletedGetApiV5ReservationRequests2668PrescriptionImagesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests2668PrescriptionImagesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests2668PrescriptionImagesGet) onCompleted;

@end