//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "Uploadradiologyrequestimagegroupfileforreservationrequestcopy.h"
#import "Listradiologyrequestimagegroupfileforreservationrequest.h"
#import "Uploadradiologyrequestimagegroupfile.h"
#import "Listradiologyrequestimagegroupfile.h"

@interface RadiologyRequestImageGroupController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests4323RadiologyRequestImageGroupsPost */
typedef void (^CompletedPostApiV5ReservationRequests4323RadiologyRequestImageGroupsPost)(BOOL success, HttpContext* context, Uploadradiologyrequestimagegroupfileforreservationrequestcopy* response, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    radiologyRequestImageGroupRadiologyRequestImagesAttributesImage    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequests4323RadiologyRequestImageGroupsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                radiologyRequestImageGroupRadiologyRequestImagesAttributesImage:(NSString*) radiologyRequestImageGroupRadiologyRequestImagesAttributesImage
                completionBlock:(CompletedPostApiV5ReservationRequests4323RadiologyRequestImageGroupsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests4323RadiologyRequestImageGroupsGet */
typedef void (^CompletedGetApiV5ReservationRequests4323RadiologyRequestImageGroupsGet)(BOOL success, HttpContext* context, Listradiologyrequestimagegroupfileforreservationrequest* response, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests4323RadiologyRequestImageGroupsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests4323RadiologyRequestImageGroupsGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5RadiologyRequestImageGroupsPost */
typedef void (^CompletedPostApiV5RadiologyRequestImageGroupsPost)(BOOL success, HttpContext* context, Uploadradiologyrequestimagegroupfile* response, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    radiologyRequestImageGroupRadiologyRequestImagesAttributesImage    Required parameter: Example: 
*/
- (void) createApiV5RadiologyRequestImageGroupsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                radiologyRequestImageGroupRadiologyRequestImagesAttributesImage:(NSString*) radiologyRequestImageGroupRadiologyRequestImagesAttributesImage
                completionBlock:(CompletedPostApiV5RadiologyRequestImageGroupsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5RadiologyRequestImageGroupsGet */
typedef void (^CompletedGetApiV5RadiologyRequestImageGroupsGet)(BOOL success, HttpContext* context, Listradiologyrequestimagegroupfile* response, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5RadiologyRequestImageGroupsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5RadiologyRequestImageGroupsGet) onCompleted;

@end