//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface ReservationRequestsController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequestsPost */
typedef void (^CompletedPostApiV5ReservationRequestsPost)(BOOL success, HttpContext* context, NSError* error);

/**
*     Create new reservation request
*     
*   URL: /reservation_requests
*   Method: POST
*   @param doctor_id
*   @param address
*   @param address_details
*   @param mobile_number
*   @param country_code
*   @param patient_latitude
*   @param patient_longitude
*   @param country_code] mobile country code
*   @header [String] X-Authentication-Token
*   @header [String] X-Session-Id
*   @return [JsonArray]  errors  ( code: 422 )
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    doctorId    Required parameter: Example: 
* @param    address    Required parameter: Example: 
* @param    addressDetails    Required parameter: Example: 
* @param    mobileNumber    Required parameter: Example: 
* @param    patientLatitude    Required parameter: Example: 
* @param    patientLongitude    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequestsPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                doctorId:(NSString*) doctorId
                address:(NSString*) address
                addressDetails:(NSString*) addressDetails
                mobileNumber:(NSString*) mobileNumber
                patientLatitude:(NSString*) patientLatitude
                patientLongitude:(NSString*) patientLongitude
                completionBlock:(CompletedPostApiV5ReservationRequestsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2685RatingsPost */
typedef void (^CompletedPostApiV5ReservationRequests2685RatingsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    ratingStars    Required parameter: Example: 
* @param    ratingReview    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequests2685RatingsPostAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                ratingStars:(NSString*) ratingStars
                ratingReview:(NSString*) ratingReview
                completionBlock:(CompletedPostApiV5ReservationRequests2685RatingsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests4142Put */
typedef void (^CompletedPutApiV5ReservationRequests4142Put)(BOOL success, HttpContext* context, NSError* error);

/**
* Doctor reject resesrvation request
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    currentStatus    Required parameter: Example: 
*/
- (void) updateApiV5ReservationRequests4142PutAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                currentStatus:(NSString*) currentStatus
                completionBlock:(CompletedPutApiV5ReservationRequests4142Put) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequestsCheckValidityCodePost */
typedef void (^CompletedPostApiV5ReservationRequestsCheckValidityCodePost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    promoCode    Required parameter: Example: 
*/
- (void) createApiV5ReservationRequestsCheckValidityCodePostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                promoCode:(NSString*) promoCode
                completionBlock:(CompletedPostApiV5ReservationRequestsCheckValidityCodePost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2668AddCaseInfoPatch */
typedef void (^CompletedPatchApiV5ReservationRequests2668AddCaseInfoPatch)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    caseInfo    Required parameter: Example: 
*/
- (void) updateApiV5ReservationRequests2668AddCaseInfoPatchAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                caseInfo:(NSString*) caseInfo
                completionBlock:(CompletedPatchApiV5ReservationRequests2668AddCaseInfoPatch) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2678Get */
typedef void (^CompletedGetApiV5ReservationRequests2678Get)(BOOL success, HttpContext* context, NSError* error);

/**
*     Create new reservation request
*     
*   URL: /reservation_requests
*   Method: POST
*   @param doctor_id
*   @param address
*   @param address_details
*   @param mobile_number
*   @param country_code
*   @param patient_latitude
*   @param patient_longitude
*   @param country_code] mobile country code
*   @header [String] X-Authentication-Token
*   @header [String] X-Session-Id
*   @return [JsonArray]  errors  ( code: 422 )
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests2678GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequests2678Get) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequests2686ShowCaseInfoGet */
typedef void (^CompletedGetApiV5ReservationRequests2686ShowCaseInfoGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequests2686ShowCaseInfoGetAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                completionBlock:(CompletedGetApiV5ReservationRequests2686ShowCaseInfoGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5ReservationRequestsGet */
typedef void (^CompletedGetApiV5ReservationRequestsGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5ReservationRequestsGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5ReservationRequestsGet) onCompleted;

@end