//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "AddnewsurgeryRequest.h"
#import "UpdatesurgeryRequest.h"

@interface SurgeriesController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5SurgeriesPost */
typedef void (^CompletedPostApiV5SurgeriesPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) createApiV5SurgeriesPostAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(AddnewsurgeryRequest*) body
                completionBlock:(CompletedPostApiV5SurgeriesPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Surgeries300Put */
typedef void (^CompletedPutApiV5Surgeries300Put)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) updateApiV5Surgeries300PutAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                contentType:(NSString*) contentType
                body:(UpdatesurgeryRequest*) body
                completionBlock:(CompletedPutApiV5Surgeries300Put) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Surgeries304Delete */
typedef void (^CompletedDeleteApiV5Surgeries304Delete)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) deleteApiV5Surgeries304DeleteAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedDeleteApiV5Surgeries304Delete) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5SurgeriesGet */
typedef void (^CompletedGetApiV5SurgeriesGet)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5SurgeriesGetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5SurgeriesGet) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5Surgeries300Get */
typedef void (^CompletedGetApiV5Surgeries300Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xSessionId    Required parameter: Example: 
* @param    xAuthenticationToken    Required parameter: Example: 
*/
- (void) getApiV5Surgeries300GetAsyncWithXSessionId:(NSString*) xSessionId
                xAuthenticationToken:(NSString*) xAuthenticationToken
                completionBlock:(CompletedGetApiV5Surgeries300Get) onCompleted;

@end