//
//  BalsameeAPIs
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CreateRequest.h"

@interface VideoExtensionController : BaseController

/**
* Completion block definition for asynchronous call to ApiV5VideoExtensionsPost */
typedef void (^CompletedPostApiV5VideoExtensionsPost)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
* @param    body    Required parameter: Example: 
*/
- (void) createApiV5VideoExtensionsPostAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                contentType:(NSString*) contentType
                body:(CreateRequest*) body
                completionBlock:(CompletedPostApiV5VideoExtensionsPost) onCompleted;

/**
* Completion block definition for asynchronous call to ApiV5VideoExtensions76Get */
typedef void (^CompletedGetApiV5VideoExtensions76Get)(BOOL success, HttpContext* context, NSError* error);

/**
* TODO: Add Description
* @param    xAuthenticationToken    Required parameter: Example: 
* @param    xSessionId    Required parameter: Example: 
* @param    contentType    Required parameter: Example: 
*/
- (void) getApiV5VideoExtensions76GetAsyncWithXAuthenticationToken:(NSString*) xAuthenticationToken
                xSessionId:(NSString*) xSessionId
                contentType:(NSString*) contentType
                completionBlock:(CompletedGetApiV5VideoExtensions76Get) onCompleted;

@end